services:
  phpipam-web:
    image: phpipam/phpipam-www:1.7x
    environment:
      - TZ=Europe/Rome
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_USER=phpipam
      - IPAM_DATABASE_PASS=SECRET
      - IPAM_DATABASE_NAME=phpipam
      - IPAM_DATABASE_WEBHOST=localhost
      - IPAM_TRUST_X_FORWARDED=true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - phpipam-logo:/phpipam/css/images/logo
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb
    networks:
      phpipam:
        aliases:
          - phpipam-web

  phpipam-cron:
    image: phpipam/phpipam-cron:1.7x
    environment:
      - TZ=Europe/Rome
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_USER=phpipam
      - IPAM_DATABASE_PASS=SECRET
      - IPAM_DATABASE_NAME=phpipam
      - SCAN_INTERVAL=1h
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - phpipam-ca:/usr/local/share/ca-certificates:ro
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    depends_on:
      - phpipam-mariadb
    networks:
      phpipam:
        aliases:
          - phpipam-cron

  phpipam-mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=SECRET
      - MARIADB_USER=phpipam
      - MARIADB_PASSWORD=SECRET
      - MARIADB_DATABASE=phpipam
    restart: unless-stopped
    volumes:
      - phpipam-db-data:/var/lib/mysql
    networks:
      phpipam:
        aliases:
          - phpipam-mariadb
  
  nginx-server:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs/
    networks:
      phpipam:
        aliases:
          - phpipam
          - phpipam.infra.vc.taurus.expert
    depends_on:
      - phpipam-web


networks:
  phpipam:
    external: true

volumes:
  phpipam-db-data:
    external: true
  phpipam-logo: 
    external: true
  phpipam-ca: 
    external: true